package database;
import model.UserKeys;
import model.RelVotoEpi;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;






//Imports para pruebas en main
import javax.sql.DataSource;

import com.mysql.jdbc.jdbc2.optional.MysqlDataSource;
//---

public class RelVotoEpiMapper extends AbstractMapper<RelVotoEpi,UserKeys>{

	public RelVotoEpiMapper(DataSource dataSource) {
		super(dataSource);
		// TODO Auto-generated constructor stub
	}

	@Override
	protected String getTableName() {
		// TODO Auto-generated method stub
		return  model.Constants.RELVOTOEPI_TABLE;
	}

	@Override
	protected String[] getColumnNames() {
		// TODO Auto-generated method stub
		return new String[]{"id_epi", "id_voto"};
	}
	
	//@SuppressWarnings("null")
	@Override
	protected RelVotoEpi buildObject(ResultSet rs) throws SQLException {
		RelVotoEpi result = new RelVotoEpi();
		result.setId_epi(rs.getLong("id_epi"));
		result.setId_voto(rs.getLong("id_voto"));
		return result;
	}

	@Override
	protected Object[] serializeKey(UserKeys key) {
		// TODO Auto-generated method stub
		return new Object[] {key.getKey(), key.getKey2() };
	}

	@Override
	protected Object[] serializeObject(RelVotoEpi object) {
		// TODO Auto-generated method stub
		return new Object[] {object.getId_voto(),object.getId_epi()};
	}

	@Override
	protected String[] getKeyColumnNames() {
		String[] keyCol={"id_epi","id_voto"};
		return keyCol;
	}

	@Override
	protected UserKeys getKey(RelVotoEpi obj) {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	protected void fill(PreparedStatement pst, RelVotoEpi obj, boolean ins) {
		try {	
			pst.setLong(1,obj.getId_voto());// ? id_voto
			pst.setLong(2, obj.getId_epi());// ? id_epi
			if(!ins){//si es update necesitamos rellenar la condicion where con el nick .
				pst.setLong(3,obj.getId_voto());// ? id_voto
				pst.setLong(4, obj.getId_epi());// ? id_epi
			}
			
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
	}

	@Override
	protected String pharseUpdate() {
		String colNam[] = getColumnNames();//adaptación a update al tener 2 claves
		String str = colNam[0]+"= ? ,"+colNam[1]+"= ? where "+colNam[0]+"= ? and "+colNam[1]+"= ?";
		return str;
	}

	@Override
	protected String pharseInsert() {
		String colNam[] = getColumnNames();
		String str = " ("+colNam[0]+","+colNam[1]+")"
		+ " values " + " ( ?  , ? ) ";
		return str;
	}

	public long getLastIndexInsert() {
		Connection con =null;
		PreparedStatement pst=null;
		ResultSet rs=null;
		Long result=null;
		try{
			con= ds.getConnection();//Attempts to establish a connection with the data source that this DataSource object represents.
			String sql="SELECT MAX( id_epi ) AS id FROM relvotoepi";
			pst = con.prepareStatement(sql);//An object that represents a pre-compiled SQL statement. 
			rs=pst.executeQuery();//Executes the SQL query in this PreparedStatement object and returns the ResultSet object generated by the query
			
			while(rs.next()){	
				result = rs.getLong("id");
			}
		}catch (SQLException e){
			e.printStackTrace();
		}finally{
			try{
				if(rs!=null) rs.close();
				if(pst!=null) pst.close();
				if(con!=null) con.close();
			}catch (Exception e){}
		}
		return result;
	}
	
	public static void main(String args[])
	        throws Exception
	    {
		//NOTA "GUARNING": Cuando se tienen varias keys, el orden que están en getColumnames() y getKeyColumNames() 
		//tiene que ser el mismo ya que se cogerán en orden para formas las condiciones el resultado de estas dos fun
	 
	 //creamos y configuramos un objeto data source:
	 MysqlDataSource mysqlDataSource = new MysqlDataSource();
	 mysqlDataSource.setServerName("localhost");
	 mysqlDataSource.setDatabaseName("practica11");
	 mysqlDataSource.setPort(3306);
	 mysqlDataSource.setUser("root");
	 mysqlDataSource.setPassword("");
	 //establecemos la conexión con la BBDD, esto ya se hace dentro de cada una de las funciones antes listadas por eso prescindimos
	 //Connection con = mysqlDataSource .getConnection();
	 
	 //creamos un usuarioMapper, pasandole un objeto DataSource
	 RelVotoEpiMapper mapVotoEpi = new RelVotoEpiMapper( mysqlDataSource);
	
	 long idV = 9223372036854775778L;//La L "the compiler will try to parse the literal as an int, hence the error message"
	 long idE=9223372036854775801L;
	 
	 //Ejemplo Insert
	 //RelVotoEpi cs=new RelVotoEpi(idV,idE);
	 //mapVotoEpi.Insert(cs);	
	 
	
	 //Ejemplo Update
	 //RelVotoEpi cs2=new RelVotoEpi(idV,idE);
	 //mapVotoEpi.update(cs2);
	 
	 //obligatorio para utiliar id´s 
	 //UserKeys keyPer = new UserKeys(idE,idV);
	  
	 //Ejemplos Delete
	 //mapVotoEpi.Delete(keyPer);
	 
	 //Ejemplos select
	 //RelVotoEpi cs3= new RelVotoEpi();
	 //cs3 = mapVotoEpi.findById(keyPer);
	
	  //System.out.println(cs3.getId_epi());
	    
	 //Ejemplo media
	// float med = mapVotoEpi.media(idE);
	 
	 // System.out.println(med);
	    
	    }

	@Override
	protected String enlace() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	protected String cond(boolean m) {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	protected String cond2(boolean m) {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	protected String cond3() {
		// TODO Auto-generated method stub
		return null;
	}
	
	
}
